In [1]:
print('Hello Python 101')

Hello Python 101


In [10]:
# type(1)
# type(True)
bool(0)

False

In [26]:
# 43+60+16+41
# 25 / 6
# 25 // 6
# 2*60+30
x = 1
y = x / 60

In [32]:
name = 'michael jackson'
even = name[::2]
sub = name[0:5:2]
name = name + ' wtvr'
upper = name.upper()

In [42]:
tuple1 = (1,2,3,4)
tuple2 = ('x', True, 2)
i = tuple1[-1]
# i
tuple3 = tuple1 + tuple2
# tuple3
tuple4 = (1,2, (True, False))
# tuple4
list1 = ['wtvr', 1,3.14]
del(list1[0])

[1, 3.14]

In [53]:
set1 = {1,2,3}
# set1
set2 = {2,3,4}
set2.add(5)
# set2
# 2 in set2
# set1 & set2
set3 = {3,4}
# set3.issubset(set2)

True

In [67]:
dict1 = {"Thriller":1982, "Back in Black":1980, "The Dark Side of the Moon":1973, "The Bodyguard":1992}
# dict1['Thriller']
dict1['Rumors']=1977
del(dict1['Thriller'])
# 'Back in Black' in dict1
# 'wtvr' in dict1
keys = dict1.keys()
values = dict1.values()

In [70]:
age = 15
if age > 18:
    print('enter')
elif age > 12 and age < 18:
    print('move to special area')
else:
    print('do not enter')

move to special area


In [71]:
squares = ['red', 'yellow', 'green', 'purple', 'blue']
for i in squares:
    print(i)

red
yellow
green
purple
blue


In [16]:
def myFunc(a):
    """
    add 1 to a
    """
    return a + 1

def collecting(*numbers):
    l = list()
    for i in numbers:
        l.append(i)
    return l

b = 1
print(myFunc(b))
mystr = 'saflaskdf'
print(len(mystr))
sortedList = [2,54,66,4,45,2,24,5,63,6,23]
sortedList.sort()
print(sortedList)
print(sorted(sortedList))
print(sum(sortedList))
print(help(myFunc))
print(collecting(1,2,3))

2
9
[2, 2, 4, 5, 6, 23, 24, 45, 54, 63, 66]
[2, 2, 4, 5, 6, 23, 24, 45, 54, 63, 66]
294
Help on function myFunc in module __main__:

myFunc(a)
    add 1 to a

None
[1, 2, 3]


In [25]:
class Circle(object):
    def __init__(self, radius, color):
        self.radius = radius
        self.color = color
        
    def add_radius(self, radius):
        self.radius += radius
        
    def get_radius(self):
        return self.radius
        
class Rectangle(object):
    def __init__(self, height, width, color):
        self.height = height
        self.width = width
        self.color = color
    
c1 = Circle(10, 'blue')
c1.add_radius(10)
c1.get_radius()
dir(c1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'add_radius',
 'color',
 'get_radius',
 'radius']

In [29]:
# file1 = open('./README.md', 'r')
with open('./README.md', 'r') as file1:
    file_stuff = file1.readline()
    print(file_stuff)

[![Open in Visual Studio Code](https://classroom.github.com/assets/open-in-vscode-c66648af7eb3fe8bc4f294546bfd86ef473780cde1dea487d3c4ff354943c9ae.svg)](https://classroom.github.com/online_ide?assignment_repo_id=8478713&assignment_repo_type=AssignmentRepo)



In [30]:
import pandas as pd

In [32]:
# csv = read_csv('./randomdata.csv')
# print(csv.head())
# print(csv.describe())
# print(csv.shape)
# print(csv['unique'].unique())

In [34]:
import numpy as np

In [44]:
arr = np.array([1,2,3,4])
print(arr[1:3])
print(arr.shape)
print(arr*2)
arr2 = np.array([2,3,5,7])
print(arr+arr2)

[2 3]
(4,)
[2 4 6 8]
[ 3  5  8 11]


In [48]:
x = np.array([[1,0], [0,1]])
y = np.array([[2,1], [1,2]])
z = x + y
print(z)
print(z.shape)
zy = np.dot(x,y)
print(zy)

[[3 1]
 [1 3]]
(2, 2)
[[2 1]
 [1 2]]
